// <auto-generated />
using System;
using MadoMagiArchive.DataServices;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MadoMagiArchive.Migrations.DataDb
{
    [DbContext(typeof(DataDbContext))]
    [Migration("20241010145015_AddFileItemWidthHeightDuration")]
    partial class AddFileItemWidthHeightDuration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("MadoMagiArchive.DataServices.DataModels.FileItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<string>("File")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Owner")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Permission")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("R18")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("File")
                        .IsUnique();

                    b.ToTable("Files");
                });

            modelBuilder.Entity("MadoMagiArchive.DataServices.DataModels.FileTag", b =>
                {
                    b.Property<int>("FileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FileOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("FileId", "TagId");

                    b.HasIndex("TagId");

                    b.HasIndex("FileId", "TagId")
                        .IsUnique();

                    b.ToTable("FileTags");
                });

            modelBuilder.Entity("MadoMagiArchive.DataServices.DataModels.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ImageFile")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Owner")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Permission")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("MadoMagiArchive.DataServices.DataModels.TagName", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lang")
                        .HasColumnType("TEXT");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.HasIndex("TagId", "Lang")
                        .IsUnique();

                    b.ToTable("TagNames");
                });

            modelBuilder.Entity("MadoMagiArchive.DataServices.DataModels.FileTag", b =>
                {
                    b.HasOne("MadoMagiArchive.DataServices.DataModels.FileItem", null)
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MadoMagiArchive.DataServices.DataModels.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MadoMagiArchive.DataServices.DataModels.TagName", b =>
                {
                    b.HasOne("MadoMagiArchive.DataServices.DataModels.Tag", null)
                        .WithMany("Names")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MadoMagiArchive.DataServices.DataModels.Tag", b =>
                {
                    b.Navigation("Names");
                });
#pragma warning restore 612, 618
        }
    }
}
